"""
Canonical paper-style 94 characteristics (conceptual) mapped to OAP / DL wide headers.

The signed_predictors_dl_wide.csv file uses PascalCase / short codes (e.g. BM, Mom6m).
This module does NOT claim perfect replication of any published 94-feature list;
it provides explicit exact + proxy mappings and tracks unresolved items via
PAPER_94_MISSING at resolution time.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

# Ordered list: Table 1 style left block (1–47) + right block (48–94), snake_case keys.
CANONICAL_PAPER_94_FEATURES: List[str] = [
    "absolute_accruals",
    "working_capital_accruals",
    "abnormal_earnings_announcement_volume",
    "years_since_first_compustat_coverage",
    "asset_growth",
    "bid_ask_spread",
    "beta",
    "beta_squared",
    "book_to_market",
    "industry_adjusted_book_to_market",
    "cash_holdings",
    "cash_flow_to_debt",
    "cash_productivity",
    "cash_flow_to_price_ratio",
    "industry_adjusted_cash_flow_to_price_ratio",
    "industry_adjusted_change_in_asset_turnover",
    "change_in_shares_outstanding",
    "industry_adjusted_change_in_employees",
    "change_in_inventory",
    "change_in_6m_momentum",
    "industry_adjusted_change_in_profit_margin",
    "change_in_tax_expense",
    "corporate_investment",
    "convertible_debt_indicator",
    "current_ratio",
    "depreciation_to_ppe",
    "dividend_initiation",
    "dividend_omission",
    "dollar_trading_volume",
    "dividend_to_price",
    "earnings_announcement_return",
    "growth_in_common_shareholder_equity",
    "earnings_to_price",
    "gross_profitability",
    "growth_in_capital_expenditures",
    "growth_in_long_term_net_operating_assets",
    "industry_sales_concentration",
    "employee_growth_rate",
    "idiosyncratic_return_volatility",
    "illiquidity",
    "industry_momentum",
    "capital_expenditures_and_inventory",
    "leverage",
    "growth_in_long_term_debt",
    "maximum_daily_return",
    "momentum_12m",
    "momentum_1m",
    "momentum_36m",
    "momentum_6m",
    "financial_statement_score",
    "size",
    "industry_adjusted_size",
    "number_of_earnings_increases",
    "operating_profitability",
    "organizational_capital",
    "industry_adjusted_pct_change_in_capex",
    "pct_change_in_current_ratio",
    "pct_change_in_depreciation",
    "pct_change_in_gross_margin_minus_pct_change_in_sales",
    "pct_change_in_quick_ratio",
    "pct_change_in_sales_minus_pct_change_in_inventory",
    "pct_change_in_sales_minus_pct_change_in_ar",
    "pct_change_in_sales_minus_pct_change_in_sga",
    "pct_change_sales_to_inventory",
    "percent_accruals",
    "price_delay",
    "financial_statements_score",
    "quick_ratio",
    "rd_increase",
    "rd_to_market_cap",
    "rd_to_sales",
    "real_estate_holdings",
    "return_volatility",
    "return_on_assets",
    "earnings_volatility",
    "return_on_equity",
    "return_on_invested_capital",
    "revenue_surprise",
    "sales_to_cash",
    "sales_to_inventory",
    "sales_to_receivables",
    "secured_debt",
    "secured_debt_indicator",
    "sales_growth",
    "sin_stocks",
    "sales_to_price",
    "volatility_of_liquidity_dollar_trading_volume",
    "volatility_of_liquidity_share_turnover",
    "accrual_volatility",
    "cash_flow_volatility",
    "debt_capacity_firm_tangibility",
    "tax_income_to_book_income",
    "share_turnover",
    "zero_trading_days",
]

# (canonical, preferred_oap_column_or_None, [proxy_oap_columns...])
_PAPER_OAP_ROWS: List[Tuple[str, Optional[str], Sequence[str]]] = [
    ("absolute_accruals", "TotalAccruals", ("Accruals", "PctAcc", "AbnormalAccruals")),
    ("working_capital_accruals", "ChNWC", ("NOA", "dNoa")),
    ("abnormal_earnings_announcement_volume", "AnnouncementReturn", ("EarnSupBig", "EarningsSurprise")),
    ("years_since_first_compustat_coverage", "FirmAge", ()),
    ("asset_growth", "AssetGrowth", ()),
    ("bid_ask_spread", "BidAskSpread", ()),
    ("beta", "Beta", ("BetaFP",)),
    ("beta_squared", None, ("Beta", "BetaFP")),
    ("book_to_market", "BM", ("BPEBM", "IntanBM")),
    ("industry_adjusted_book_to_market", "IntanBM", ("BMdec", "BM")),
    ("cash_holdings", "Cash", ()),
    ("cash_flow_to_debt", "CF", ("NetDebtFinance", "XFIN")),
    ("cash_productivity", "CashProd", ()),
    ("cash_flow_to_price_ratio", "cfp", ("CF", "IntanCFP")),
    ("industry_adjusted_cash_flow_to_price_ratio", "IntanCFP", ("cfp",)),
    ("industry_adjusted_change_in_asset_turnover", "ChAssetTurnover", ()),
    ("change_in_shares_outstanding", "ShareIss1Y", ("ShareIss5Y", "CompEquIss")),
    ("industry_adjusted_change_in_employees", "hire", ("ChNAnalyst",)),
    ("change_in_inventory", "ChInv", ()),
    ("change_in_6m_momentum", "Mom6m", ("IntMom",)),
    ("industry_adjusted_change_in_profit_margin", "ChInvIA", ("OperProf",)),
    ("change_in_tax_expense", "ChTax", ("Tax",)),
    ("corporate_investment", "Investment", ("InvGrowth", "InvestPPEInv")),
    ("convertible_debt_indicator", "ConvDebt", ()),
    ("current_ratio", None, ("NOA", "DelCOL")),
    ("depreciation_to_ppe", None, ("PctTotAcc",)),
    ("dividend_initiation", "DivInit", ()),
    ("dividend_omission", "DivOmit", ()),
    ("dollar_trading_volume", "DolVol", ()),
    ("dividend_to_price", "DivYieldST", ("PayoutYield", "NetPayoutYield")),
    ("earnings_announcement_return", "AnnouncementReturn", ()),
    ("growth_in_common_shareholder_equity", "ChEQ", ("NetEquityFinance",)),
    ("earnings_to_price", "EP", ("IntanEP", "FEPS")),
    ("gross_profitability", "GP", ("OperProf",)),
    ("growth_in_capital_expenditures", "grcapx", ("grcapx3y", "GrAdExp")),
    ("growth_in_long_term_net_operating_assets", "GrLTNOA", ()),
    ("industry_sales_concentration", "Herf", ("HerfAsset", "HerfBE")),
    ("employee_growth_rate", "hire", ()),
    ("idiosyncratic_return_volatility", "IdioVolAHT", ("IdioVol3F", "RealizedVol")),
    ("illiquidity", "Illiquidity", ()),
    ("industry_momentum", "IndMom", ("IndRetBig",)),
    ("capital_expenditures_and_inventory", "InvestPPEInv", ("InvGrowth",)),
    ("leverage", "Leverage", ("BookLeverage", "OPLeverage")),
    ("growth_in_long_term_debt", "DebtIssuance", ("CompositeDebtIssuance", "NetDebtFinance")),
    ("maximum_daily_return", "MaxRet", ()),
    ("momentum_12m", "Mom12m", ("Mom12mOffSeason",)),
    ("momentum_1m", "REV6", ("MRreversal", "LRreversal")),
    ("momentum_36m", None, ("Mom12m", "LRreversal", "TrendFactor")),
    ("momentum_6m", "Mom6m", ("Mom6mJunk",)),
    ("financial_statement_score", "OScore", ("PredictedFE", "Frontier")),
    ("size", "AM", ("MS", "AOP")),
    ("industry_adjusted_size", "HerfBE", ("Herf",)),
    ("number_of_earnings_increases", "NumEarnIncrease", ("EarningsStreak",)),
    ("operating_profitability", "OperProf", ("CBOperProf", "OperProfRD")),
    ("organizational_capital", "OrgCap", ()),
    ("industry_adjusted_pct_change_in_capex", "grcapx", ("grcapx3y",)),
    ("pct_change_in_current_ratio", None, ("DelCOL", "ChNWC")),
    ("pct_change_in_depreciation", None, ("PctTotAcc",)),
    ("pct_change_in_gross_margin_minus_pct_change_in_sales", "GrSaleToGrOverhead", ()),
    ("pct_change_in_quick_ratio", None, ("DelCOL",)),
    ("pct_change_in_sales_minus_pct_change_in_inventory", "GrSaleToGrInv", ()),
    ("pct_change_in_sales_minus_pct_change_in_ar", None, ("DelCOA",)),
    ("pct_change_in_sales_minus_pct_change_in_sga", None, ("GrSaleToGrOverhead",)),
    ("pct_change_sales_to_inventory", None, ("ChInv",)),
    ("percent_accruals", "PctAcc", ("PctTotAcc", "Accruals")),
    ("price_delay", "PriceDelayRsq", ("PriceDelaySlope", "PriceDelayTstat")),
    ("financial_statements_score", "PredictedFE", ("OScore",)),
    ("quick_ratio", None, ("DelCOL", "NOA")),
    ("rd_increase", "SurpriseRD", ("RD", "PatentsRD")),
    ("rd_to_market_cap", "RDcap", ()),
    ("rd_to_sales", "RDS", ("RD",)),
    ("real_estate_holdings", "realestate", ()),
    ("return_volatility", "RealizedVol", ("VolSD", "VarCF")),
    ("return_on_assets", "roaq", ()),
    ("earnings_volatility", "VarCF", ("RealizedVol", "VolSD")),
    ("return_on_equity", "RoE", ()),
    ("return_on_invested_capital", None, ("OperProf", "GP")),
    ("revenue_surprise", "RevenueSurprise", ("EarningsSurprise",)),
    ("sales_to_cash", None, ("SP", "cfp")),
    ("sales_to_inventory", None, ("ChInv", "GrSaleToGrInv")),
    ("sales_to_receivables", None, ("DelCOA",)),
    ("secured_debt", None, ("BookLeverage", "CredRatDG")),
    ("secured_debt_indicator", None, ("CredRatDG",)),
    ("sales_growth", "MeanRankRevGrowth", ()),
    ("sin_stocks", "sinAlgo", ()),
    ("sales_to_price", "SP", ("IntanSP",)),
    ("volatility_of_liquidity_dollar_trading_volume", "VolMkt", ("DolVol", "VolumeTrend")),
    ("volatility_of_liquidity_share_turnover", "ShareVol", ("std_turn", "RIO_Turnover")),
    ("accrual_volatility", "VolSD", ("VarCF", "PctAcc")),
    ("cash_flow_volatility", "VarCF", ("VolSD",)),
    ("debt_capacity_firm_tangibility", "tang", ()),
    ("tax_income_to_book_income", "Tax", ("EBM",)),
    ("share_turnover", "std_turn", ("ShareVol", "RIO_Turnover")),
    ("zero_trading_days", "zerotrade1M", ("zerotrade6M", "zerotrade12M")),
]

def _build_maps() -> Tuple[Dict[str, Optional[str]], Dict[str, List[str]]]:
    exact: Dict[str, Optional[str]] = {}
    proxies: Dict[str, List[str]] = {}
    for canon, pref, prox in _PAPER_OAP_ROWS:
        exact[canon] = pref
        proxies[canon] = list(prox)
    return exact, proxies


PAPER_94_TO_OAP209_MAP: Dict[str, Optional[str]] = _build_maps()[0]
PAPER_94_PROXY_MAP: Dict[str, List[str]] = _build_maps()[1]

# Additional OAP columns to include when feature set = paper_94_plus_oap_extras
OAP_EXTRA_FEATURES: List[str] = [
    "MomVol",
    "ResidualMomentum",
    "IntMom",
    "Coskewness",
    "ReturnSkew",
    "skew1",
    "BetaTailRisk",
    "ProbInformedTrading",
    "OptionVolume1",
    "ShortInterest",
    "IO_ShortInterest",
]

FEATURE_SET_OPTIONS: Tuple[str, ...] = (
    "paper_94_exact_only",
    "paper_94_exact_plus_proxy",
    "paper_94_plus_oap_extras",
    "oap_all_numeric_pruned",
)

DEFAULT_FEATURE_SET: str = "paper_94_exact_plus_proxy"

# Placeholder: use FeatureResolutionSummary.missing_canonical at runtime.
PAPER_94_MISSING: tuple = ()
